# rbldns-static stack example
# STACK_BASE_PATH [base folder where to host files, must exists]
# STACK_BASE_PATH=folder_for_stack ; mkdir -p ${STACK_BASE_PATH}/data

version: '3.7'

x-environment: &common-vars
    TZ: Europe/Rome
    ZONES: /zones
    NS_SERVERS: 127.0.0.1
    RBL_DOMAIN: bl.localhost.tld
    USERNAME: rbldns

services:
  rbldns:
    image: neomediatech/rbldns-static
    hostname: rbldns
    environment:
      << : *common-vars    
    volumes:
      - zones:${ZONES:-/zones}
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

volumes:
  zones:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/data
